### ISSUE TITLE
Why? Author.create!(author_params)

### ISSUE THREAD

**Issue by rogerprz** [learn-co-curriculum/validations-in-controller-actions-rails-lab#7]
The lab provides    **@author = Author.create!(author_params)** as the def create info for author class controller, but if we are not going to use it why provide it all. 

Thanks

**Comment by cjbrock** [comment]
Hi @rogercodes1! A lot of times when you get into the later sections of the course, your labs will be building on themselves. So while you won't use the methods you build in the current lab, you might use the methods in later labs.  It's also good practice of the skills that you have learned up to this point. 

// Corinna
