### ISSUE TITLE
Migration errors

### ISSUE THREAD

**Issue by zlehmann** [learn-co-curriculum/validations-in-controller-actions-rails-lab#8]
The two migration files in this lab do not have the Migration[4.2] designation which leads to errors when you try to migrate. I added the [4.2] to the end to get everything to work.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
