### ISSUE TITLE
ThreadError: already initialized occurring with Ruby 2.6 and rails < 5

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/validations-in-controller-actions-rails-lab#9]
__Summary:__ Students are experiencing a `ThreadError: already initialized` when attempting `learn` tests when using Ruby 2.6 and Rails 4.2 (or any Rails < 5). It seemed to be associated with [this github issue](https://github.com/rails/rails/issues/34790)

__Repeatability:__ After fixing a sub-issue with this lab (deleting the Gemfile.lock and specifying `gem 'sqlite3', '~> 1.3.6'`  in the `Gemfile`), this problem __is repeatable__ by running this lab with Ruby 2.6.  Note that it is probably prudent to also fix the sqlite3 Gemfile/Gemfile.lock issue.

__Solution:__ Updating to Rails 5 (in Gemfile) and changing the rspec tests so that all params passed to a route are in a nested hash `{params: { params1: value1, params2: value2}} solved the issue.

**Comment by maxwellbenton** [comment]
Hi @micahshute,

Thank you for spotting this, providing feedback and steps to recreate. We've updated this lesson to Rails 5 and fixed the controller tests and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
